baseURL: https://senvang.org/
languageCode: en-us
title: senvang.org
theme: senvang

params:
  themeColor: blue
  favicon: img/favicon.png
  centerTheme: true

languages:
  en:
    languageName: English
    title: senvang.org

    params:
      logo:
        logoText: SENVANG IT Solutions | Stefan RÃ¶mer
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: about me
        url: /about
        weight: 1
      - identifier: business
        name: business
        url: /business
        weight: 2
      - identifier: contact
        name: contact
        url: /contact
        weight: 3
      - identifier: experience
        name: experience
        url: /experience
        weight: 3
      - identifier: git
        name: git
        url: https://git.senvang.org/user/login/
        weight: 4
